[package]
name = "ffplayout-engine"
description = "24/7 playout based on rust and ffmpeg"
license = "GPL-3.0"
authors = ["Jonathan Baecker jonbae77@gmail.com"]
readme = "README.md"
version = "0.9.5"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = { version = "3.1", features = ["derive"] }
crossbeam-channel = "0.5"
ffprobe = "0.3"
file-rotate = { git = "https://github.com/BourgondAries/file-rotate.git" }
jsonrpc-http-server = "18.0"
lettre = "0.10.0-rc.6"
log = "0.4"
notify = "4.0"
once_cell = "1.10"
rand = "0.8"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
shlex = "1.1"
simplelog = { version = "^0.12", features = ["paris"] }
time = { version = "0.3", features = ["formatting", "macros"] }
walkdir = "2"

[target.x86_64-unknown-linux-musl.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[[bin]]
name = "ffplayout"
path = "src/main.rs"

[profile.release]
opt-level = 3
strip = true
lto = true

# DEBIAN DEB PACKAGE
[package.metadata.deb]
name = "ffplayout-engine"
priority = "optional"
section = "net"
license-file = ["LICENSE", "0"]
depends = ""
suggests = "ffmpeg"
copyright = "Copyright (c) 2022, Jonathan Baecker. All rights reserved."
conf-files = ["/etc/ffplayout/ffplayout.yml"]
assets = [
    [
        "target/x86_64-unknown-linux-musl/release/ffplayout",
        "/usr/bin/ffplayout",
        "755"
    ],
    ["assets/ffplayout.yml", "/etc/ffplayout/ffplayout.yml", "644"],
    ["assets/logo.png", "/usr/share/ffplayout/logo.png", "644"],
    ["README.md", "/usr/share/doc/ffplayout-engine/README", "644"],
]
systemd-units = { unit-name = "ffplayout-engine", unit-scripts = "assets", enable = false }

# REHL RPM PACKAGE
[package.metadata.generate-rpm]
name = "ffplayout-engine"
license = "GPL-3.0"
assets = [
    { source = "target/x86_64-unknown-linux-musl/release/ffplayout", dest = "/usr/bin/ffplayout", mode = "755" },
    { source = "assets/ffplayout.yml", dest = "/etc/ffplayout/ffplayout.yml", mode = "644", config = true },
    { source = "assets/ffplayout-engine.service", dest = "/lib/systemd/system/ffplayout-engine.service", mode = "644" },
    { source = "README.md", dest = "/usr/share/doc/ffplayout-engine/README", mode = "644", doc = true },
    { source = "LICENSE", dest = "/usr/share/doc/ffplayout-engine/LICENSE", mode = "644" },
    { source = "assets/logo.png", dest = "/usr/share/ffplayout/logo.png", mode = "644" },
]
