name: rust
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: On all Systems
        run: |
          rustup update stable
          rustup component add rustfmt
          rustup component add clippy

      - name: Use ffmpeg on Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: FedericoCarboni/setup-ffmpeg@v1

      - name: Tests and Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          cargo test --all-features
          cargo clippy --all-features --all-targets -- --deny warnings
          cargo fmt --all -- --check

      - name: Run build on all Systems
          cargo build --all-features
